### ISSUE TITLE
Scrolling on SplashGallery considered slow

### ISSUE THREAD

**Issue by xiaoas** [noname-v2/noname-v2.github.io#3]
要是不停的用滚轮，每次滚动画都会卡住，不是特别美好。
这是个小bug

**Comment by noname-v2** [comment]
卡住是指什么？浏览器是哪个版本？

**Comment by xiaoas** [comment]
滚一下->速度增加->速度减小

滚一下->速度增加--再滚一下->速度归0后增加->速度减小

显得很卡顿

Google Chrome	91.0.4472.124 (Official Build) (64-bit)

**Comment by noname-v2** [comment]
我没遇到过，滚轮是普通滚轮吗？能不能录下屏？

**Comment by noname-v2** [comment]
另外有没有尝试重置过？目前更新都需要点一下重置。

**Comment by xiaoas** [comment]
是的 鼠标滚轮 录屏怕是没法在今天给到，

点了重置。

**Comment by noname-v2** [comment]
更新了下，应该稍微好点了，不过貌似没有特别完美的办法。

**Comment by xiaoas** [comment]
太强了🤣我原本以为加个isScrolling的tag就解决了。
